[versions]

compileSdk = "34"
targetSdk = "34"
minSdk = "24"
fragment = "1.6.2"
appcompat = "1.6.1"
kotlin = "1.9.22"
material = "1.11.0"
constraintlayout = "2.1.4"
navigation = "2.7.6"
retrofit = "2.9.0"
hilt = "2.50"
gson = "2.9.0"
jackson = "2.8.1"
interceptor = "4.12.0"
timber = "5.0.1"
leak = "2.13"
glide = "4.16.0"
keyboard = "3.0.0-RC2"
viewmodel = "2.6.2"
motion = "2.0.0-beta4"
fcm = "23.4.0"
analytics = "21.5.0"
crashlytics = "18.6.0"
zxing = "1.9.13"
coroutine = "1.7.3"
dataStore = "1.0.0"
room = "2.6.1"
paging = "3.2.1"
#test
junit = "4.13.2"
mockito = "4.8.0"
archCore = "2.2.0"
robolectric = "4.11.1"
ktlintPlugin = "12.1.0"
androidGradle = "8.2.1"
gms = "4.4.0"
maptiler ="11.13.0"

[libraries]
androidGradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradle" }
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gms = { module = "com.google.gms:google-services", version.ref = "gms" }

fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }

#design
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

#navigation
navigation = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigationUi = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

#network
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "gson" }
interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "interceptor" }

#log
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
zxing = { module = "me.dm7.barcodescanner:zxing", version.ref = "zxing" }

#leak
leak = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leak" }

#glide
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

#keyboard
keyboard = { module = "net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent", version.ref = "keyboard" }

#Hilt 
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltSupport = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hiltGradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }

#viewModel
#            lifecycleExt   ="androidx.lifecycle:lifecycle-extensions", version.ref = "viewmodel"
viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "viewmodel" }
liveData = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "viewmodel" }

jackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "jackson" }
fcm = { module = "com.google.firebase:firebase-messaging", version.ref = "fcm" }
coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }

#firebase analytics
analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "analytics" }
crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "crashlytics" }

#Data store
dataStore = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }

#Room
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
roomTesting = { module = "androidx.room:room-testing", version.ref = "room" }

#Paging3
paging = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }

#test
junit = { module = "junit:junit", version.ref = "junit" }
androidxJunit = { module = "androidx.test.ext:junit", version = "1.1.5" }
androidxEspressoCore = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
maptiler = { module = "org.maplibre.gl:android-sdk",version.ref = "maptiler" }
coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutine" }
archCoreTesting = { module = "androidx.arch.core:core-testing", version.ref = "archCore" }
mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "4.1.0" }
mockitoInline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
ktlintGradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlintPlugin" }

[bundles]
common = [
    "fragment",
    "appcompat",
    "kotlin",
    "material",
    "constraintlayout",
    "dataStore",
    "timber",
    "hilt",
    "viewmodel"]
navigation = ["navigation", "navigationUi"]
network = ["retrofit", "gson", "interceptor"]
